name: ht_auth_inmemory
description: A Very Good Project created by Very Good CLI.
repository: https://github.com/headlines-toolkit/ht-auth-inmemory
publish_to: none

environment:
  sdk: ^3.8.0

dependencies: 
  ht_auth_client:
    git:
      url: https://github.com/headlines-toolkit/ht-auth-client.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
  uuid: ^4.5.1
      
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0
